version: 2.1

parameters:
  run_backend-canada-develop:
    type: boolean
    default: false
  run_frontend-canada-develop:
    type: boolean
    default: false
  run_backend-canada-prod:
    type: boolean
    default: false
  run_frontend-canada-prod:
    type: boolean
    default: false

jobs:
  job_deploy_backend:
    docker:
      - image: cimg/python:3.8
    parameters:
      app_name:
        type: string
      env_name:
        type: string
      dry_run:
        type: boolean
        default: true
    environment:
      APP_NAME: << parameters.app_name >>
      ENV_NAME: << parameters.env_name >>
      DRY_RUN: << parameters.dry_run >>
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            echo "env: ${ENV_NAME} - ${DRY_RUN}"


workflows:
  version: 2
  "run_backend-canada-develop":
    jobs:
      - job_deploy_backend:
          name: job_deploy_backend_dry_run-canada-develop
          dry_run: true
          app_name: cue-health-api
          env_name: canada-develop
          filters:
            branches:
              ignore:
                - main
      - job_deploy_backend:
          name: job_deploy_backend-canada-develop
          app_name: cue-health-api
          env_name: canada-develop
          filters:
            branches:
              only:
                - main

  "run_backend-canada-prod":
    jobs:
      - job_deploy_backend:
          name: job_deploy_backend_dry_run-canada-prod
          dry_run: true
          app_name: cue-health-api
          env_name: canada-prod
          filters:
            branches:
              ignore:
                - main
      - hold:
          type: approval
          requires:
           -  job_deploy_backend-canada-prod
      - job_deploy_backend:
          name: job_deploy_backend-canada-prod
          app_name: cue-health-api
          env_name: canada-prod
          filters:
            branches:
              only:
                - main
          requires:
           - hold